export { default as Overview } from './Overview';
export { default as StudentManagement } from './StudentManagement';
export { default as StudentDetail } from './StudentDetail';
export { default as CourseManagement } from './CourseManagement';
export { default as CourseDetail } from './CourseDetail';
export { default as PaymentManagement } from './PaymentManagement';
export { default as TeacherManagement } from './TeacherManagement';
export { default as StudioManagement } from './StudioManagement';
export { default as StudioDetail } from './StudioDetail';
