export const PAYMENT_TYPE = {
    CARD: 'CARD',
    PRIVATE: 'PRIVATE',
    DROP_IN: 'DROP_IN',
};

export const PAYMENT_TYPES = ['CARD', 'PRIVATE', 'DROP_IN'];

export const DANCE_ROLE = {
    LEADER: 'LEADER',
    FOLLOWER: 'FOLLOWER',
    SOLO: 'SOLO',
};

export const DANCE_ROLES = [
    DANCE_ROLE.LEADER,
    DANCE_ROLE.FOLLOWER,
    DANCE_ROLE.SOLO,
];

export const PARTICIPANT_STATUS = {
    PRESENT: 'PRESENT',
    ABSENT: 'ABSENT',
};

export const PARTICIPANT_STATUSES = [
    PARTICIPANT_STATUS.PRESENT,
    PARTICIPANT_STATUS.ABSENT,
];
