export const PAYMENT_TYPE = {
    CARD: 'CARD',
    PRIVATE: 'PRIVATE',
    DROP_IN: 'DROP_IN',
};

export const PAYMENT_TYPES = ['CARD', 'PRIVATE', 'DROP_IN'];

export const DANCE_ROLE = {
    LEADER: 'LEADER',
    FOLLOWER: 'FOLLOWER',
    SOLO: 'SOLO',
};

export const DANCE_ROLES = [
    DANCE_ROLE.LEADER,
    DANCE_ROLE.FOLLOWER,
    DANCE_ROLE.SOLO,
];

export const PARTICIPANT_STATUS = {
    PRESENT: 'PRESENT',
    ABSENT: 'ABSENT',
    NOT_LOGGED: 'NOT_LOGGED',
};

export const PARTICIPANT_STATUSES = [
    PARTICIPANT_STATUS.PRESENT,
    PARTICIPANT_STATUS.ABSENT,
    PARTICIPANT_STATUS.NOT_LOGGED,
];

export const COURSE_STUDENT_STATUS = {
    ACTIVE: 'ACTIVE',
    INACTIVE: 'INACTIVE',
    WAITLIST: 'WAITLIST',
};

export const COURSE_STUDENT_STATUSES = [
    COURSE_STUDENT_STATUS.ACTIVE,
    COURSE_STUDENT_STATUS.INACTIVE,
    COURSE_STUDENT_STATUS.WAITLIST,
];

export const COURSE_DAY = {
    MON: 'MON',
    TUE: 'TUE',
    WED: 'WED',
    THU: 'THU',
    FRI: 'FRI',
    SAT: 'SAT',
    SUN: 'SUN',
};

export const COURSE_DAYS = [
    COURSE_DAY.MON,
    COURSE_DAY.TUE,
    COURSE_DAY.WED,
    COURSE_DAY.THU,
    COURSE_DAY.FRI,
    COURSE_DAY.SAT,
    COURSE_DAY.SUN,
];
